version: "3"
services:
  app:
    image: ismailcharfi/mp-cicd:latest
    ports:
      - "5050:5050"
    depends_on:
      - mongodb
    environment:
      PORT: 5050
      DB_URL: mongodb://mongodb:27017/mp
  mongodb:
    container_name: mp-mongodb
    image: "mongo"
    ports:
      - "27017:27017"
