version: "3"
services:
  app:
    container_name: mp-app
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "start"]
    ports:
      - "5050:5050"
    depends_on:
      - mongodb
    environment:
      PORT: 5050
      DB_URL: mongodb://mongodb:27017/mp
  mongodb:
    container_name: mp-mongodb
    image: "mongo"
    ports:
      - "27017:27017"
  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
