global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['mp-app:5050']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
